----creating a date base using name SQLBasic

create database SQL_Basic

---DATA PREPARATION AND UNDERSTANDING
---Q1.What is the total number of rows in each of the 3 tables in the database?

--- No. of rows in customer table
select COUNT(*) from Customer

--- No. of rows in product_cat_info table
select COUNT(*) from prod_cat_info

--- No. of rows in transactions table
select COUNT(*) from Transactions

---Q2.What is the total number of transactions that have a return?

select count(Total_amt) from Transactions
where total_amt like '-%'

---Q3.As you would have noticed, the dates provided across the datasets are not in a correct format.As first steps, pls convert the date variables into valid date formats before proceeding ahead.

select convert(date,DOB,105) DATE_ from Customer
select convert(date,tran_date,105) TRANS_DATE from Transactions

---Q4.What is the time range of the transaction data available for analysis? Show the output in number of days, months and years simultaneously in different columns.

select DATEDIFF(day,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) Days from Transactions 
select DATEDIFF(MONTH,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) Months from Transactions
select DATEDIFF(YEAR,min(convert(date,tran_date,105)),max(convert(date,tran_date,105))) Year from Transactions

---Q5.Which product category does the sub-category “DIY” belong to?

select prod_cat from prod_cat_info
where prod_subcat = 'DIY'

---DATA ANALYSIS

---Q1.Which channel is most frequently used for transactions?
 
select top 1 Store_type,count(transaction_id) [Amount] from transactions
group by Store_type
order by [amount] desc

---Q2.What is the count of Male and Female customers in the database?

select Gender, count(customer_Id)[Count] from Customer
where Gender in ('M','F')
group by Gender

---Q3.From which city do we have the maximum number of customers and how many?

select top 1 city_code,count(customer_Id) [count] from Customer
group by city_code
order by [count] desc

---Q4.How many sub-categories are there under the Books category?

select prod_cat,count(prod_subcat) [subcategories] from prod_cat_info
where prod_cat = 'Books'
group by prod_cat

---Q5.What is the maximum quantity of products ever ordered?

select top 1 Qty from Transactions
order by Qty desc

---Q6.What is the net total revenue generated in categories Electronics and Books?

select SUM(total_amt) [AMOUNT] from Transactions T
INNER JOIN [prod_cat_info] P on T.prod_cat_code = P.prod_cat_code
AND T.prod_subcat_code = P.prod_sub_cat_code
Where prod_cat in ('Books','Electronics')

---Q7.How many customers have >10 transactions with us, excluding returns?

select count(customer_Id) AS CUSTOMER_COUNT
from Customer where customer_Id IN 
(Select cust_id from Transactions
LEFT JOIN Customer ON customer_Id = cust_id
where total_amt not like '-%'
group by cust_id
having COUNT(transaction_id) > 10)


---Q8.What is the combined revenue earned from the “Electronics” & “Clothing” categories,from “Flagship stores”?

select sum(total_amt)[revenue] from Transactions t 
inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
and t.prod_subcat_code = p.prod_sub_cat_code
where prod_cat in ('Electronics', 'Clothing') and Store_type ='Flagship store'

---Q9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.

select prod_subcat, sum(total_amt)[revenue] from Transactions t
left join Customer c on t.cust_id = c.customer_Id
left join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
and t.prod_subcat_code = p.prod_sub_cat_code
where prod_cat='Electronics' and gender = 'M'
group by prod_subcat

---Q10.What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?

select top 5 prod_subcat_code,(sum(total_amt)/(Select sum(Total_amt) from Transactions))*100 AS Percent_of_sale, 
(COUNT (CASE WHEN QTY< 0 THEN QTY ELSE NULL END)/SUM(QTY))*100 AS PERCENTAGE_OF_RETURN
from Transactions t inner join Customer c on t.cust_id = c.customer_Id 

group by prod_subcat_code
order by sum(total_amt) desc



---Q11.For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 30 days of transactions from max transaction date available in the data?

select cust_id,sum(total_amt) as revenue from Transactions
where cust_id in (select cust_id from Transactions
where DATEDIFF(year,convert(date,DOB,103), getdate()) between 25 and 35)
and convert(date,tran_date,103) between DATEADD(day,-30,(select max(convert(date,tran_date,103)) from Transactions))
and (select max(convert(date,tran_date,103)) from Transactions)
group by cust_id




---Q12.Which product category has seen the max value of returns in the last 3 months of transactions?


select top 1 prod_cat, sum(total_amt) amount from Transactions t
inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
and t.prod_subcat_code = p.prod_sub_cat_code
where total_amt < 0 and
CONVERT(date,tran_date,103) between DATEADD(month,-3,(select max(convert(date,tran_date,103)) from Transactions))
 and (select max(convert(date,tran_date,103)) from Transactions)
 group by prod_cat
 order by sum(total_amt) desc



---Q13.	Which store-type sells the maximum products; by value of sales amount andby quantity sold?

select Store_type, sum(total_amt) Total_sales, sum(Qty) Total_Qty
from Transactions
group by Store_type
having sum(total_amt) >= all(select sum(total_amt) from Transactions group by Store_type)
and sum(Qty) >= all (select sum(Qty) from Transactions group by Store_type)

---Q14.What are the categories for which average revenue is above the overall average.

select prod_cat, avg(total_amt) Average_amt from Transactions t 
inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
and t.prod_subcat_code = p.prod_sub_cat_code
group by prod_cat
having avg(total_amt) > (select avg(total_amt) Average_amt from Transactions)

---Q15.Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.

select top 5 prod_cat,prod_subcat ,avg(total_amt) Average_revenue, sum(total_amt) Total_Revenue 
from Transactions t inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code and
t.prod_subcat_code = p.prod_sub_cat_code
where prod_cat in (select top 5 prod_cat from Transactions t 
inner join prod_cat_info p on t.prod_cat_code = p.prod_cat_code
group by prod_cat
order by sum(qty) desc)
group by prod_cat,prod_subcat

